# Generated by Django 3.1.7 on 2021-04-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_constituent_town_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituent',
            name='town_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.town'),
        ),
    ]
