# Generated by Django 3.1.7 on 2021-04-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_constituent_town_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituent',
            old_name='town',
            new_name='arr',
        ),
    ]
