# Generated by Django 3.1.7 on 2021-04-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210407_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituent',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.town'),
        ),
    ]
