# Generated by Django 3.1.7 on 2021-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210407_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituent',
            name='area',
        ),
        migrations.AddField(
            model_name='constituent',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='users.Area'),
        ),
        migrations.RemoveField(
            model_name='constituent',
            name='town',
        ),
        migrations.AddField(
            model_name='constituent',
            name='town',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='users.Town'),
        ),
    ]
