# Generated by Django 3.1.7 on 2021-05-04 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210407_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mp_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
