# Generated by Django 3.1.7 on 2021-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210504_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subadmin',
            field=models.BooleanField(default=False),
        ),
    ]
