# Generated by Django 3.1.7 on 2021-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_permission_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='permission_name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
