# Generated by Django 3.1.7 on 2021-05-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210504_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPermissions',
            new_name='UserPermissionCust',
        ),
    ]
