# Generated by Django 3.2.2 on 2021-05-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210504_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subadmin_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subadmins', to='users.constituency'),
        ),
    ]
