# Generated by Django 3.1.7 on 2021-03-11 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp_operations', '0002_project_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.customuser'),
        ),
    ]
