# Generated by Django 3.1.7 on 2021-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0003_auto_20210311_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='mp_projects/'),
        ),
    ]
