# Generated by Django 3.1.7 on 2021-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0004_auto_20210313_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='project', to='mp_operations.Comment'),
        ),
    ]
