# Generated by Django 3.1.7 on 2021-04-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp_operations', '0005_auto_20210327_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
