# Generated by Django 3.1.7 on 2021-04-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0009_auto_20210403_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
    ]
