# Generated by Django 3.1.7 on 2021-04-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210407_1005'),
        ('mp_operations', '0013_project_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanAreaSummaryForMp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='action_plan/')),
                ('date', models.DateField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency')),
            ],
        ),
    ]
