# Generated by Django 3.1.7 on 2021-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0014_actionplanareasummaryformp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(max_length=10000),
        ),
    ]
