# Generated by Django 3.2.2 on 2021-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0015_auto_20210503_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageActionPlanStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_number', models.IntegerField()),
                ('total_value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='actionplanareasummaryformp',
            name='comment',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
