# Generated by Django 3.2.2 on 2021-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0016_auto_20210512_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
    ]
