# Generated by Django 3.1.7 on 2021-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0002_incidentreport_mpsassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
