# Generated by Django 3.1.7 on 2021-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0003_auto_20210327_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
