# Generated by Django 3.1.7 on 2021-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0004_incidentreport_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
