# Generated by Django 3.1.7 on 2021-04-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210407_1005'),
        ('constituent_operations', '0005_message_date_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanToAssemblyMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=100)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_rating', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency')),
            ],
        ),
    ]
