# Generated by Django 3.1.7 on 2021-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0007_auto_20210409_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='message',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
