# Generated by Django 3.1.7 on 2021-04-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0008_auto_20210409_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsForActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
            ],
        ),
    ]
