# Generated by Django 3.2.2 on 2021-05-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0013_actionplanparticipants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionplanparticipants',
            options={'verbose_name_plural': 'Action Plan Participants'},
        ),
    ]
