# Generated by Django 3.2.2 on 2021-05-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0017_project_is_post'),
        ('users', '0014_auto_20210504_1458'),
        ('constituent_operations', '0014_alter_actionplanparticipants_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_operations.project')),
            ],
        ),
    ]
