# Generated by Django 3.2.2 on 2021-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0015_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
