# Generated by Django 3.2.2 on 2021-05-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0018_assessmentparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpsAssessment',
        ),
    ]
