# Generated by Django 3.2.2 on 2021-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0020_conductassessment_conductsforassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductassessment',
            name='conduct',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
